### ISSUE TITLE
Error 'ConnectionOptions' object has no attribute 'model' since v2.1.0

### ISSUE THREAD

**Issue by dginzbourg** [graphql-python/graphene-sqlalchemy#146]
We started getting the following error after upgrade to v2.1.0:
```
 File "/usr/local/lib/python3.6/site-packages/graphql/type/definition.py", line 235, in define_field_map
	    field_map = field_map()
	  File "/usr/local/lib/python3.6/site-packages/graphene/types/typemap.py", line 271, in construct_fields_for_type
	    field = get_field_as(field.get_type(self.schema), _as=Field)
	  File "/usr/local/lib/python3.6/site-packages/graphene/types/dynamic.py", line 22, in get_type
	    return self.type()
	  File "/usr/local/lib/python3.6/site-packages/graphene_sqlalchemy/converter.py", line 37, in dynamic_type
	    return createConnectionField(_type._meta.connection)
	  File "/usr/local/lib/python3.6/site-packages/graphene_sqlalchemy/fields.py", line 101, in createConnectionField
	    return __connectionFactory(_type)
	  File "/opt/h2o-iceberg/internal_api/sortable_connection_field.py", line 88, in __init__
	    model = type._meta.model
	AttributeError: 'ConnectionOptions' object has no attribute 'model'
```
Downgrading to v2.0.0 solved the problem. We work with latest Flask-GraphQL & sqlalchemy
Thanks

**Comment by erikwrede** [comment]
Hey, if this error still persists in newer versions, please open a new issue including a minimal example explaining what you are trying to achieve. I will close the issue since it's been over 4 years, but I'm happy to assist if you still have issues!
