### ISSUE TITLE
Tests fail with SQLAlchemy 1.4

### ISSUE THREAD

**Issue by UjinT34** [graphql-python/graphene-sqlalchemy#304]
Tests fail with SQLAlchemy 1.4:

```
ERROR collecting graphene_sqlalchemy/tests/test_converter.py
ImportError while importing test module 'graphene-sqlalchemy/graphene_sqlalchemy/tests/test_converter.py'.                                                                                                                    
Hint: make sure your test modules/packages have valid Python names.                                                               
Traceback:                                                                                                                        
graphene_sqlalchemy/tests/test_converter.py:9: in <module>                                                                        
    from sqlalchemy_utils import ChoiceType, JSONType, ScalarListType                                                             
.tox/py39/lib/python3.9/site-packages/sqlalchemy_utils/__init__.py:1: in <module>                                                 
    from .aggregates import aggregated  # noqa                                                                                    
.tox/py39/lib/python3.9/site-packages/sqlalchemy_utils/aggregates.py:372: in <module>                                             
    from .functions.orm import get_column_key
.tox/py39/lib/python3.9/site-packages/sqlalchemy_utils/functions/__init__.py:1: in <module>
    from .database import (  # noqa
.tox/py39/lib/python3.9/site-packages/sqlalchemy_utils/functions/database.py:10: in <module>
    from ..expressions import explain_analyze
.tox/py39/lib/python3.9/site-packages/sqlalchemy_utils/expressions.py:4: in <module>
    from sqlalchemy.sql.expression import (
E   ImportError: cannot import name '_literal_as_text' from 'sqlalchemy.sql.expression' (graphene-sqlalchemy/.tox/py39/lib/python3.9/site-packages/sqlalchemy/sql/expression.py)
```

https://github.com/sqlalchemy/sqlalchemy/commit/f07e050c9ce4afdeb9c0c136dbcc547f7e5ac7b8

The library itself seems to work fine with batching disabled.

**Comment by tad3j** [comment]
I've noticed the same with batching. I think the reason is that they changed `QueryContext` in v1.4 SQLAlchemy:

v1.3 usage (used by this lib): https://github.com/graphql-python/graphene-sqlalchemy/blob/20ecaeadf2144b88555a3daf1a04e31b7f2ff95a/graphene_sqlalchemy/batching.py#L55

v1.4 usage: https://github.com/sqlalchemy/sqlalchemy/blob/cb8906bab1776bafed48ef69ded0768461f7e7b8/lib/sqlalchemy/orm/query.py#L2939

Notice that in v1.4 `QueryContext` accepts many argumetns while in v1.3 only a single one.

Any plans to update this lib to work with 1.4?

**Comment by raguiar2** [comment]
Is a release going to be cut with this feature? It would be useful to have the most up-to-date version of graphene-sqlalchemy on pypi so it can be used with 1.4

**Comment by HansG89** [comment]
What about this issue? Still same behavior in latest version. Batching with sqlalchemy 1.4 not working

**Comment by erikwrede** [comment]
The graphene-sqlalchemy v3 beta release contains this fix.

**Comment by jaredculp** [comment]
Bump on the question above. Could this fix be released to the 2.x branch?

**Comment by erikwrede** [comment]
@jaredculp What is your blocker for upgrading to graphene 3 (apart from the SQLAlchemy beta status, which is now actively being brought towards release)? 

I'm asking because focusing on backporting will reduce my time for working on the 3.0 release, so unless there's a compelling reason, I sadly cannot focus on more versions than 3.0. 
But as stated before, I'd welcome and support any efforts on backporting this.
